# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-use_db}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Stevenson", "George 'Jake' Wendt"]
  s.date = %q{2010-12-03}
  s.description = %q{Gem version of use_db rails plugin}
  s.email = %q{github@jake.otherinbox.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
    "app/helpers/application_helper.rb",
    "app/models/alpha.rb",
    "app/models/beta.rb",
    "app/models/gamma.rb",
    "app/models/normal.rb",
    "config/routes.rb",
    "lib/tasks/use_db_tasks.rake",
    "lib/use_db.rb",
    "lib/use_db/configurations.rb",
    "lib/use_db/migration.rb",
    "lib/use_db/override_fixtures.rb",
    "lib/use_db/override_test_case.rb",
    "lib/use_db/tasks.rb",
    "lib/use_db/test_model.rb",
    "lib/use_db/use_db_plugin.rb",
    "lib/use_db/use_db_test.rb"
  ]
  s.homepage = %q{http://github.com/jakewendt/use_db}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gem version of use_db rails plugin}
  s.test_files = [
    "test/unit/alpha_test.rb",
    "test/unit/beta_test.rb",
    "test/unit/gamma_test.rb",
    "test/unit/normal_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
    else
      s.add_dependency(%q<rails>, ["~> 2"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2"])
  end
end

